# Generated by Django 2.0.6 on 2018-06-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='OneWeb',
        ),
    ]
